### ISSUE TITLE
store datasets in doi-based directory structure and move path definition to parent class

### ISSUE THREAD

**Issue by le-ander** [theislab/sfaira#108]

**Comment by le-ander** [comment]
@davidsebfischer would we still allow overriding this by the user with a custom fn?
I'm not sure if that's really needed still as we have automated basically everything in the data repo management by now.
self.path as the parten directory to the sfaira repo is of course always user defined

**Comment by davidsebfischer** [comment]
I think this will be an attribute of the loading class. In principle, it could be ignored in favour of an absolute path to some local directory in a private data loader, other than that I would say we enforce usage of this now because distribution of custom paths to Datasets is otherwise too complicated. In the future, we could think about creating symbolic links for data sets that are already somewhere else on disk.

**Comment by davidsebfischer** [comment]
>  In the future, we could think about creating symbolic links for data sets that are already somewhere else on disk.

@Zethson maybe something to add to the CLI as a separate function? this would have an argument `dir`and would create the sfaira managed directory as a symbolic link? This way sfaira `download` would then skip re-downloading this data.

**Comment by Zethson** [comment]
> > In the future, we could think about creating symbolic links for data sets that are already somewhere else on disk.
> 
> @Zethson maybe something to add to the CLI as a separate function? this would have an argument `dir`and would create the sfaira managed directory as a symbolic link? This way sfaira `download` would then skip re-downloading this data.

Sure, why not.
