### ISSUE TITLE
CI checks in pull request always run twice

### ISSUE THREAD

**Issue by le-ander** [theislab/sfaira#132]
I noticed that whenever I push to a branch of an open pull request, all github actions checks are run twice (once triggered by push and once triggered by pull_request)

could we somehow have these checks run only once in sucha scenario @Zethson ?

**Comment by Zethson** [comment]
Unfortunately not. By design actually.
Although, these checks look like they are the same they are not: Please have a look at https://github.community/t/duplicate-checks-on-push-and-pull-request-simultaneous-event/18012/3 

" On push checks the branch code, and on pull_request checks the pre-merge code. "

We could reduce the run overhead with https://github.com/marketplace/actions/skip-duplicate-actions maybe, but currently it's working as intended.
