### ISSUE TITLE
change default search strategy order in cell mapping suggestions

### ISSUE THREAD

**Issue by le-ander** [theislab/sfaira#144]
From working with the cell map suggestions for a while, I noticed that in 90+% of the cases, the first hit of the second matching group (i.e. the term after the first `:|||:`is usually the one I'm looking for. @davidsebfischer could we switch the order of the matching strategies, so that this second search strategy comes first by default? this would improve the user experience quite a bit I think. or am I missing something here? :)

**Comment by davidsebfischer** [comment]
Yeah so far I did this on purpose because the first group would show hits where somebody forgot about specifying the anatomics sub type of a label , eg. `lung fibroblast` is likely more desirable a match to `fibroblast`, than `fibroblast` is, if the sample is from the lung, and if these don't come first people will likely not look for them. But I am also ok with switching it.

**Comment by le-ander** [comment]
hm, okay now actually also encountered a situation where the organ specific one gave me a better match. I guess let's not switch for now.
