### ISSUE TITLE
Provide conda environment that is sufficient for the CLI

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/sfaira#319]
**Is your feature request related to a problem? Please describe.**
I ran into some issues with pip vs conda installed packages when running the CLI.

**Describe the solution you'd like**
Maybe a YAML?

**Comment by Zethson** [comment]
Into what issues did you run?
A fresh conda environment + pip installing sfaira must work.
Mixing Conda & pip installed packages has always been dangerous because they use different resolvers for the dependencies. However, we would need to bring sfaira to conda for this to work, which is ugly and difficult and I certainly won't do that haha

**Comment by davidsebfischer** [comment]
Yeah no I wouldnt want to push it on conda right now! New enviornment sovled it, not sure what was going on there before because I was only using pip. Thanks!
