### ISSUE TITLE
Feature request: faster import

### ISSUE THREAD

**Issue by ivirshup** [theislab/sfaira#324]
**Is your feature request related to a problem? Please describe.**

It's very slow to import `sfaira`. This includes any use of the command line interface. For example:

```sh
$ time sfaira --help
...
sfaira --help  28.27s user 1.04s system 106% cpu 27.624 total
```

```python
%time import sfaira
```

**Describe the solution you'd like**

Faster import of Sfaira by delaying computation of whatever is taking so long.

**Additional context**

It looks to me like this is mostly coming from this line: 

https://github.com/theislab/sfaira/blob/dab9cb3f6d89dc6c6b52f9ce23c9a7e938e4d91b/sfaira/consts/__init__.py#L5

and the subsequent loading of a bunch of ontologies. Here's the first couple lines of `%prun -s cumtime import sfaira` for evidence that this is the culprit:

```
         46387199 function calls (46339180 primitive calls) in 33.690 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      276    0.005    0.000   38.698    0.140 __init__.py:1(<module>)
        7    0.001    0.000   33.802    4.829 __init__.py:2(<module>)
   4477/1    0.029    0.000   33.693   33.693 {built-in method builtins.exec}
   3377/1    0.014    0.000   33.693   33.693 <frozen importlib._bootstrap>:986(_find_and_load)
   3364/1    0.010    0.000   33.693   33.693 <frozen importlib._bootstrap>:956(_find_and_load_unlocked)
   3166/1    0.011    0.000   33.693   33.693 <frozen importlib._bootstrap>:650(_load_unlocked)
   2975/1    0.006    0.000   33.693   33.693 <frozen importlib._bootstrap_external>:842(exec_module)
   5107/1    0.003    0.000   33.693   33.693 <frozen importlib._bootstrap>:211(_call_with_frames_removed)
        1    0.000    0.000   30.572   30.572 ontologies.py:10(__init__)
        6    0.000    0.000   29.722    4.954 base.py:551(__init__)
        6    0.045    0.008   29.722    4.954 base.py:512(__init__)
        6    0.657    0.109   29.677    4.946 read.py:12(read_obo)
        6    1.020    0.170   28.010    4.668 read.py:63(get_sections)
```

**Comment by davidsebfischer** [comment]
Hi @ivirshup, thanks for looking into it, I completely agree that `OCS` most likely takes most of the import time on all platforms. This is by design right now, but there may be a more optimal solution. Brief context: OCS harbors ontology containers that are used by many class instances thoughtout sfaira, often also of classes that are instantiated in the backend of sfaira.data and not explicitly by the user, resulting in a large number of instances. This results in some operations taking unnecessarily long because they require many ontology container initialisations. This is why we decided to instantiate it once globally upon import so that all subsequent use cases are fast. The only alternative I can come up with is:

- instantiate globally upon first use (this will most likely be the first call to sfaira so little gained in overall run time but the run time distribution away from import may be more intuitive to handle for packages extending sfaira)

I havent dont this yet because it does not actually speed up sfaira usage but it is something we could discuss. Also happy to hear other ideas!

**Comment by Zethson** [comment]
This is especially an issue with the CLI because it at some point imports the whole sfaira package. Therefore, every command takes like 20 seconds just because of the imports. A more modular structure will help with this, but still.

Maybe the costly functions/imports must be a separate function that the user has to call to speed up the imports?

**Comment by davidsebfischer** [comment]
We could keep the OCS constant but only populate it with the intialised ontologies based on a particular function call, `sfaira.initialise()` for example.

**Comment by le-ander** [comment]
I guess not all CLI commands actually use the OCS. coulnd't we somehow internally prevend the OCS form being initialised in certain cases so that we don't need to introduce another command?

**Comment by davidsebfischer** [comment]
I guess we can make it an object that appears like a constant but is actually no initialised once it s called for the firsts time.

**Comment by le-ander** [comment]
sound like black magic? :D how would you do this?

**Comment by Zethson** [comment]
`@click.version_option(sfaira.__version__, message=click.style(f'sfaira Version: {sfaira.__version__}', fg='blue'))`

This is where we import the whole sfaira package. The CLI needs to know the version of sfaira. Of course possible to move where the version is saved, but it is currently in the "standard" place....

**Comment by davidsebfischer** [comment]
Currently, it s a class instance with ontology instances attributes that initialised in the constructor. That could work by turning the attributes into cached properties that are only loaded once: upon first call when the caching attribute is still empty.

**Comment by davidsebfischer** [comment]
@Zethson can you check if the referenced fix in the PR works for CLI case? I think that should work.

**Comment by Zethson** [comment]
```
from sfaira import __version__

@click.version_option(__version__, message=click.style(f'sfaira Version: {__version__}', fg='blue'))
```

Maybe this does not import the whole package? If it does it speeds up things.

**Comment by Zethson** [comment]
https://github.com/theislab/sfaira/commit/c26c0dbbbcf07cc82169a960a70ea6f88595af64
