### ISSUE TITLE
Cell ontology present online but not in sfaira

### ISSUE THREAD

**Issue by Hrovatin** [theislab/sfaira#631]
I found this cell type online https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0004823 , but when I use the name I get
`ValueError: 'intrahepatic bile duct epithelium' is not a valid entry for cell_type in data set`

**Comment by davidsebfischer** [comment]
I do not think that this is a cell type but instead a tissue (also based on the name `epithelium` rather than `epithelial cell`), if you look closely on the website above it is in UBERON and not included in the CL graph as a child of cell. It is listed under CL in this link because CL has links to UBERON to link cell types to their resident tissues, these nodes do not have CL IDs and are not children of "cell", they are just shipped with CL so that you can query these related ontology elements..

**Comment by Hrovatin** [comment]
Thanks!
