### ISSUE TITLE
Tutorial availability?

### ISSUE THREAD

**Issue by ivirshup** [theislab/sfaira#64]
Hey, just checking out this package, but I can't access any of the tutorials. The links just result in 404 responses on nbviewer. It looks like they are pointing to a repo called `theislab/sfaira_tutorials`, but I can't find that repo (maybe I just don't have access).

**Comment by davidsebfischer** [comment]
Hi @ivirshup! We have not made it public yet, we are waiting for #38 to be merged which should be done fist half of this week and will quickly check all tutorials based on these changes. We are doing this because #38 introduces structural changes that will improve contribution of data loaders a lot. I will post here again once we made this public!

**Comment by Zethson** [comment]
https://github.com/theislab/sfaira_tutorials

@ivirshup public now.
