### ISSUE TITLE
self.annotated

### ISSUE THREAD

**Issue by le-ander** [theislab/sfaira#81]
I remember we deprecated self.annotated because we now have self.obs_key_cellontology_original set
I still get an error though when loading datasets. Could we automatically set self.annotated in the backend based on whether self.obs_key_cellontology_original is not None?

```pytb
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-9132565d77c9> in <module>
      1 # pick a specific dataset and check if it has celltype annotations (in case that matters to you)
----> 2 ds.flatten().datasets['mouse_pancreas_2019_10x_thompson_004_10.1016/j.cmet.2019.01.021'].annotated

/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py in annotated(self)
    845         else:
    846             if self.meta is None:
--> 847                 self.load_meta(fn=None)
    848             if self.meta is not None and self._ADATA_IDS_SFAIRA.annotated in self.meta.columns:
    849                 return self.meta[self._ADATA_IDS_SFAIRA.annotated]

/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py in load_meta(self, fn)
    743                     # Make sure None entries are formatted as None and not as string "None":
    744                     meta[k] = [None if x == "None" else x for x in meta[k].values.tolist()]
--> 745             self.meta = meta
    746 
    747     def write_meta(

/storage/groups/ml01/code/leander.dony/sfaira/sfaira/data/base.py in meta(self, x)
   1041                     if x[k] is not None:  # None is always allowed.
   1042                         if not isinstance(v[0], self._META_DATA_FIELDS[k]):
-> 1043                             raise ValueError(f"key {k} of signature {str(v[0])} "
   1044                                              f"in meta data table did not match signature "
   1045                                              f"{str(self._META_DATA_FIELDS[k])}")

ValueError: key annotated of signature None in meta data table did not match signature <class 'bool'>
```

**Comment by davidsebfischer** [comment]
It s not an issue with the attribute `annotated` as such, which still exists, but the its exception of returning `None`which seems to have been triggered during meta data writing here, your code is picking up this unexpected `None`when loading this meta data. So we have to fix this exception, as the annotated attribute should never be `None`and will be fine then.

**Comment by le-ander** [comment]
I see. Makes sense that it's none now as it's never set after being initialised as none. So we'd just set it based on self.obs_key_cellontology_original I guess?

**Comment by le-ander** [comment]
ok so seems like there is a bug in the dataloader of the mouse pancreas datasets (d10_1016_j_cmet_2019_01_021) that causes this behaviour. we should probably just be setting self.obs_key_cellontology_original in the dataloader to start with?

**Comment by davidsebfischer** [comment]
The behaviour of `.annotated` here was correct, during raw loading, the attributes indicating annotation were not set in the constructor and meta data were not available yet, so this was saved as `None` in meta data. This was however a bug in the particular data loader, which should have set these attributes. 

In a case in which there is no annotation available, `obs_key_cellontology_original` is not set. If meta data are not yet available, we should return None here because it s not clear yet whether this attribute would only be specified upon first loading, e.g. for automated data loaders for 3rd party data bases. If the meta data are loaded, we can return the correponding entry from there.

During meta data writing, we have however executed `._load()` already, so if cell types are not indicated at this point, they are never present. So assuming that these data loaders set `obs_key_cellontology_original` latest in `._load()`, the current code works, with the exception of:

- [ ] `.annotated` returning `None` as above only if `._load()`has not been triggered yet, ie if `.adata` is None and `False`(no annotation) otherwise
- [ ] the bug int he specific data loader.

This wil then also resolve the issue with None type in meta data frame which expects `bool`, `annotated` can return `None`but not during meta data writing, so this should never arrive there during meta data loading.
